fastlane_version "2.62.1"
default_platform :ios

platform :ios do
  lane :beta do
    cert
    sigh(force: true)
    build_app(scheme: "EpiReader", export_method: "app-store")
    pilot(skip_waiting_for_build_processing: true)
  end

  lane :release do
    gym(scheme: "EpiReader") # Build your app - more options available
    deliver(force: true)
  end
end
